package edu.mci.management.api.domain;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

@Entity
@Data
@NoArgsConstructor
public class GameServer {

    public GameServer(String name, String uri,int maxPlayers) {
        this.name = name;
        this.uri = uri;
        this.status = GameServerState.LOBBY;
        this.maxPlayers = maxPlayers;
        this.currentPlayerCount = 0;
        this.lastSeen = Instant.now();
    }

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Schema(description = "Autogenerated UUID",
            example = "a1b2c3d4-e5f6-11eb-b8bc-0242ac130003",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private UUID id;

    @Column(nullable = false)
    @Schema(example = "MCI Pro Labyrinth", requiredMode = Schema.RequiredMode.REQUIRED)
    private String name;

    @Column(nullable = false)
    @Schema(example = "ws://play.example.com:9000 oder ws:192.168.0.1:9000", requiredMode = Schema.RequiredMode.REQUIRED)
    private String uri;

    @Column(nullable = false)
    @Schema(example="2", requiredMode = Schema.RequiredMode.REQUIRED)
    private int currentPlayerCount;

    @Column(nullable = false)
    @Schema(example="4", requiredMode = Schema.RequiredMode.REQUIRED)
    private int maxPlayers;

    @Column(nullable = false)
    @Schema(example="2025-10-07T14:12:00Z", requiredMode = Schema.RequiredMode.REQUIRED)
    private Instant lastSeen;

    @Column(nullable = false)
    @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
    private GameServerState status;
}
