name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine version from tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG=${TAG#v}
          echo "VERSION=${TAG}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build management.api (Maven)
        run: mvn -B -DskipTests -Drevision=${{ env.VERSION }} -f management.api/pom.xml package

      - name: Find built JAR
        id: find_jar
        run: echo "JAR_PATH=$(ls management.api/target/*.jar | head -n 1)" >> $GITHUB_ENV

      - name: Create GitHub Release and attach JAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.VERSION }}
          files: ${{ env.JAR_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
