name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine version from tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG=${TAG#v}
          echo "VERSION=${TAG}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build management.api (Maven)
        run: mvn -B -DskipTests -Drevision=${{ env.VERSION }} -f management.api/pom.xml package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: management-api-jar
          path: management.api/target/*.jar

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_artifact.outputs.asset_path }}
          asset_name: management-api.jar
          asset_content_type: application/java-archive
